var faq2 = {
  'How many types of   Stopover Holiday packages are there?': 'There are three types of   Stopover Holiday packages:Basic   Stopover Holiday,  Stopover Holiday,  Stopover Premium',
  'How do I book a   Stopover Holiday?': 'If you’ve already booked a flight on our website or through your local   Airlines office, simply enter your Booking Reference in the ‘Manage Booking’ section of this website. You can add a   Stopover Holiday to your booking there, as long as:your itinerary includes a stop of at least 24 hours in   (or else, changes to your flight will be necessary); and your booking is made at least 72 hours prior to the hotel check-in date.  Stopover Holiday packages can’t be purchased from the SIA Stopover Holiday counter.',
  'What personal information should I provide?': 'You’re required to provide your:full name (as in your passport) flight details, including the date you arrive in   length of stay preferred hotel, with one or two alternatives choice of single, twin or triple occupancy',
  'Will I get a receipt after purchasing a   Stopover Holiday?': 'Yes, you will receive a receipt via email. You’re encouraged to print a copy of the receipt for your reference.You will also receive a Virtual Multi-Purpose Document (vMPD) or Electronic Miscellaneous Document (EMD), which states the name of your confirmed hotel and return airport transfers. Print a copy of this and present it to the ground operator and hotel when you arrive. If you’re unable to produce these documents, the hotel may charge you the published room rate instead of the preferred   Stopover Holiday rate.',
  'What happens when I arrive at   Changi Airport? ': 'Whether you arrive at Terminal 2 or 3, proceed to the SIA Stopover Holiday counter to present your documents and the ground operator will assist you.',
  'What do the complimentary return airport transfers comprise?': 'Airport transfers are provided in an air-conditioned coach or minibus. When you arrive at the SIA Stopover Holiday counter, the ground operator will book your return airport transfers. A change in pick-up time is subject to availability. Please contact the ground operator at:Transfers Hotline 6732 7928 (8am to 8pm daily) 9145 8660 (after 8pm)'
}

var faq1 = {
  'What is online/mobile check-in?': 'Online/Mobile check-in means checking in for your flight through our website or  Air mobile app. Eligible passengers may also obtain a self-printed boarding pass or mobile boarding pass when departing from selected cities.',
  'Am I eligible for online/mobile check-in?': 'Online/Mobile check-in is available to all passengers, except those who: are below 18 years old, and not accompanied by an adult passenger (above 18 years old) are travelling in a group of 10 passengers or more in the same booking have one or more preceding flights in the same booking for which the passengers have not checked in.',
  'I have bags to check in. Can I still check in online?': 'Yes, you can check in on our website or through the  Air mobile app, get your self-printed or mobile boarding pass, and proceed to the airport check-in counter on the day of your departure to drop off your bags. If you are departing from  , London or Copenhagen, you may use the check-in kiosks to print your baggage tag(s) before proceeding to the bag drop counter to drop off your bags.',
  'Why do I have to enter my passport information when I check in online?': 'For security reasons, immigration and customs authorities go through a comprehensive process of checking the personal details you provide before you arrive. It’s important for you to ensure the information you provide is correct and up-to-date, as any inaccuracies may cause delays in immigration clearance and other inconveniences when you arrive at the airport. The passport details you provide should also be that of the passport you’ll carry with you when you travel.',
  'When is my online/mobile check-in complete?': 'Your check-in is complete once you arrive at the confirmation page online. Depending on your city of departure, you may be eligible for self-printed or mobile boarding passes. If so, these boarding passes will be available for download and/or printing. Find out the cities where you’ll be eligible for self-printed boarding passes and mobile boarding passes.',
  'What types of boarding passes are available?': 'There are four types of boarding passes:Boarding passes that are printed and issued at the airport check-in counterSelf-printed boarding passes in PDF format, which can be printed at your convenience Mobile boarding passes, issued on your mobile device with a QR code Kiosk boarding passes, which are printed at the airport check-in kiosks (where available)',
  'Why should I get a self-printed or mobile boarding pass?': 'Printing your boarding pass or downloading it to your mobile device before you go to the airport will help you avoid the queue at the check-in counter. If you have bags to check in or travel documents to verify, you can proceed to the bag drop counters. If you don’t, you can proceed directly to immigration.Some airports may require you to verify your travel documents at the check-in counter even if you have obtained your self-printed or mobile boarding passes. Please check with the airline or airport customer service counter if unsure.',
  'What if I cannot print or download my boarding pass?': 'If you’re unable to print your boarding pass or get it on your mobile device, you can get your boarding pass from the airport check-in counter on the day of your departure. Please be at the airport counter at least 90 minutes before your flight if you have bags to check in. If you have no bags to check in, please collect your boarding pass before closure of check-in counters. If your boarding pass isn’t collected by then, your check-in may be cancelled and your seat may be reassigned. For the opening hours of   Airlines check-in counters at airports around the world, click here.',
  'My self-printed boarding pass says I should proceed to the check-in counter at the airport, but I’m late for my flight. Can I proceed directly to immigration?': 'No. If you do so, the airport police officer will redirect you to the check-in counter for verification.',
  'If I choose to receive my check-in confirmation via SMS, will I be charged for the service?': 'We won’t charge you for this service. However, your mobile operator may charge you for SMS delivery, especially if you’re away from your residential country. You’re advised not to reply to the check-in confirmation SMS, as this could incur more charges from your mobile operator.',
  'I’ve downloaded a mobile boarding pass. Why am I also given a printed boarding pass at the check-in counter at Changi Airport?': 'You may receive a printed boarding pass at the airport check-in counter if you’ve requested a change of seat or if operational factors, such as a change of aircraft, require it.',
  'Where are the   Airlines check-in kiosks located?': 'The   Airlines check-in kiosks are located at the following airports:   Changi Terminal 2 (Row 3) and Terminal 3 (Rows 3 and 4) Amsterdam Schiphol (Departure Hall 3) Copenhagen London Heathrow Terminal 2 (Zone A)',
  'Why can’t I complete my check-in at the check-in kiosk?': 'You’ll need to approach the airport check-in counter if: your passport or visa is not machine-readable your booking is not confirmed, or you’re on a waitlist you or the passenger you’re checking in is an unaccompanied minor you’ve booked an extra seat (for instance, for a musical instrument) you require special assistance (for instance, you’re travelling with a pet, you require medical assistance, or you’ve requested for the meet-and-assist service)'
}

var cities = {

}
